In [12]:
import glob
import os
import pandas as pd
import json
from datetime import datetime

In [3]:
not_ordered_files = []
start_times = []
all_windows = []
i = 0
for folder in sorted(glob.glob("/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/*/")):
    context_file = os.path.join(folder, "context.json")
    with open(context_file, 'r') as ctx_file:
        js = json.load(ctx_file)
        start_times.append(js["start time"])
        not_ordered_files.append(folder)

In [3]:
sorted_time_file_pairs = sorted(zip(start_times, not_ordered_files),
                                key=lambda pair:datetime.strptime(pair[0], "%H:%M:%S"))

In [4]:
sorted_files = [pair[1] for pair in sorted_time_file_pairs]
sorted_files

['/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/01/',
 '/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/07/',
 '/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/03/',
 '/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/10/',
 '/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/13/',
 '/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/20/',
 '/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/08/',
 '/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/19/',
 '/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/18/',
 '/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/02/',
 '/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/21/',
 '/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/12/',
 '/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/16/',
 '/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/04/',
 '/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/17/',
 '/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/09/',
 '/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/15/',
 '/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/11/',
 '/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/05/',
 '/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/14/',
 '/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/06/']

In [5]:
file = '/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/01/'
csv_file = os.path.join(file, "data.csv")
df = pd.read_csv(csv_file)
df.head()

,uid,time,sensor,action,Subject,Description,activity
0,0,07:22:45,bedroom_1 door,OPENED,A,"After getting up in the morning, A opens the d...",6
1,1,07:22:49,bedroom_1 door,CLOSED,A,A walks out of bedroom_1 and then closes the d...,6
2,2,07:22:55,bathroom global mov,turned ON,A,"After leaving bedroom_1, A walks into the bath...",1
3,3,07:23:04,bathroom toilet contact,CLOSED,A,A starts using the toilet in the bathroom.,1
4,4,07:23:16,bedroom_1 door,OPENED,B,"After getting up in the morning, B opens the d...",6

In [6]:
activity_file = "/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/activities.json"
activities_df = pd.read_json(activity_file)
activities_df.head()

   id                 name                                        description
0   0               others
1   1         using toilet
2   2     preparing drinks  making coffee, brewing tea, taking a beverage ...
3   3  preparing breakfast
4   4     having breakfast

In [7]:
activities_df.iloc[0,0]

np.int64(0)

In [8]:
activity = activities_df[activities_df['id']==1].name.item()
type(activity)

str

In [9]:
activity

'using toilet'

In [10]:
events = []
for file in sorted_files:
    print(file)
    csv_file = os.path.join(file, "data.csv")
    print(csv_file)
    df = pd.read_csv(csv_file)
    for _, row in df.iterrows():
        activity_id = int(row["activity"])
        activity = activities_df[activities_df['id']==activity_id].name.item()
        events.append(
            {
                "time": str(row['time']),
                "sensor": str(row["sensor"]),
                "sensor_status": str(row["action"]), 
                "subject": str(row["Subject"]),
                "activity": activity,
                "description": str(row["Description"])
            }
        )

/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/01/
/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/01/data.csv
/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/07/
/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/07/data.csv
/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/03/
/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/03/data.csv
/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/10/
/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/10/data.csv
/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/13/
/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/13/data.csv
/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/20/
/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/20/data.csv
/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/08/
/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/08/data.csv
/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/19/
/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/19/data.csv
/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/18/
/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/18/data.csv
/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/02/
/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/02/data.csv
/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/21/
/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/21/data.csv
/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/12/
/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/12/data.csv
/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/16/
/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/16/data.csv
/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/04/
/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/04/data.csv
/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/17/
/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/17/data.csv
/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/09/
/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/09/data.csv
/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/15/
/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/15/data.csv
/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/11/
/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/11/data.csv
/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/05/
/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/05/data.csv
/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/14/
/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/14/data.csv
/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/06/
/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/MuRAL/06/data.csv

In [11]:
events[-1]

{'time': '23:39:43',
 'sensor': 'bedroom_1 door',
 'sensor_status': 'CLOSED',
 'subject': 'B',
 'activity': 'bedroom personal activity',
 'description': 'B enters bedroom_1, closes the door, and prepares to rest and sleep for the night.'}

In [27]:
# Not creating windows of data.
with open("/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/data_preprocessing/preprocessed_data.json", "w") as f:
    json.dump(events, f, indent=4)

In [28]:
len(events)

8635

In [32]:
data_train = events[0: int(len(events)*0.95)]
len(data_train)

8203

In [37]:
with open("/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/data_preprocessing/preprocessed_train_data.json", 'w') as f:
    json.dump(data_train, f, indent=4)

In [38]:
data_test = events[int(len(events)*0.95):]
len(data_test)

432

In [39]:
with open("/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR/data_preprocessing/preprocessed_test_data.json", 'w') as f:
    json.dump(data_test, f, indent=4)

In [ ]:
with open("preprocess_data.json", "w") as f:
    json.dump(all_windows, f, indent=4)

In [14]:
with open("/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR_Sima/data_preprocessing/preprocessed_train_data.json", 'r') as f:
    har_data = json.load(f)
har_data

[{'time': '07:22:45',
  'sensor': 'bedroom_1 door',
  'sensor_status': 'OPENED',
  'subject': 'A',
  'activity': 'bedroom personal activity',
  'description': 'After getting up in the morning, A opens the door to bedroom_1.'},
 {'time': '07:22:49',
  'sensor': 'bedroom_1 door',
  'sensor_status': 'CLOSED',
  'subject': 'A',
  'activity': 'bedroom personal activity',
  'description': 'A walks out of bedroom_1 and then closes the door.'},
 {'time': '07:22:55',
  'sensor': 'bathroom global mov',
  'sensor_status': 'turned ON',
  'subject': 'A',
  'activity': 'using toilet',
  'description': 'After leaving bedroom_1, A walks into the bathroom.'},
 {'time': '07:23:04',
  'sensor': 'bathroom toilet contact',
  'sensor_status': 'CLOSED',
  'subject': 'A',
  'activity': 'using toilet',
  'description': 'A starts using the toilet in the bathroom.'},
 {'time': '07:23:16',
  'sensor': 'bedroom_1 door',
  'sensor_status': 'OPENED',
  'subject': 'B',
  'activity': 'bedroom personal activity',
  'description': 'After getting up in the morning, B opens the door to bedroom_1.'},
 {'time': '07:23:19',
  'sensor': 'bathroom toilet contact',
  'sensor_status': 'OPENED',
  'subject': 'A',
  'activity': 'using toilet',
  'description': 'A finishes using the toilet in the bathroom.'},
 {'time': '07:23:20',
  'sensor': 'bedroom_1 door',
  'sensor_status': 'CLOSED',
  'subject': 'B',
  'activity': 'bedroom personal activity',
  'description': 'B walks out of bedroom_1 and then closes the door.'},
 {'time': '07:23:25',
  'sensor': 'bedroom_2 door',
  'sensor_status': 'OPENED',
  'subject': 'B',
  'activity': 'bedroom personal activity',
  'description': 'B arrives at the doorway of bedroom_2, then after closing the door, opens the door to bedroom_2.'},
 {'time': '07:23:25',
  'sensor': 'bathroom sink mov',
  'sensor_status': 'turned ON',
  'subject': 'A',
  'activity': 'using toilet',
  'description': 'After using the toilet, A washes hands in the bathroom sink.'},
 {'time': '07:23:32',
  'sensor': 'bedroom_2 door',
  'sensor_status': 'CLOSED',
  'subject': 'B',
  'activity': 'bedroom personal activity',
  'description': 'After getting up in bedroom_2, B closes the door to bedroom_2 and leaves.'},
 {'time': '07:23:38',
  'sensor': 'bathroom sink mov',
  'sensor_status': 'turned OFF',
  'subject': 'A',
  'activity': 'using toilet',
  'description': 'A finishes washing hands in the bathroom sink.'},
 {'time': '07:23:38',
  'sensor': 'kitchen sink mov',
  'sensor_status': 'turned ON',
  'subject': 'B',
  'activity': 'preparing breakfast',
  'description': 'B arrives at the kitchen sink and starts washing hands.'},
 {'time': '07:23:54',
  'sensor': 'kitchen sink mov',
  'sensor_status': 'turned OFF',
  'subject': 'B',
  'activity': 'preparing breakfast',
  'description': 'B finishes washing hands.'},
 {'time': '07:23:54',
  'sensor': 'bathroom global mov',
  'sensor_status': 'turned OFF',
  'subject': 'A',
  'activity': 'using toilet',
  'description': 'A leaves the bathroom and moves to the kitchen.'},
 {'time': '07:24:00',
  'sensor': 'kitchen cabinet door',
  'sensor_status': 'OPENED',
  'subject': 'B',
  'activity': 'preparing breakfast',
  'description': 'B crouches down and opens the kitchen cabinet door.'},
 {'time': '07:24:01',
  'sensor': 'kitchen cabinet door',
  'sensor_status': 'CLOSED',
  'subject': 'B',
  'activity': 'preparing breakfast',
  'description': 'After taking out a sauce pan, B closes the kitchen cabinet door.'},
 {'time': '07:24:02',
  'sensor': 'kitchen counter mov',
  'sensor_status': 'turned ON',
  'subject': 'A',
  'activity': 'preparing drinks',
  'description': 'A takes a dish from the dish drying rack on the kitchen counter.'},
 {'time': '07:24:04',
  'sensor': 'kitchen sink mov',
  'sensor_status': 'turned ON',
  'subject': 'B',
  'activity': 'preparing breakfast',
  'description': 'B uses the freshly taken sauce pan in the kitchen sink to get water.'},
 {'time': '07:24:06',
  'sensor': 'kitchen sink mov',
  'sensor_status': 'turned OFF',
  'subject': 'B',
  'activity': 'preparing breakfast',
  'description': 'B uses the freshly taken sauce pan in the kitchen sink to get water.'},
 {'time': '07:24:07',
  'sensor': 'kitchen sink mov',
  'sensor_status': 'turned ON',
  'subject': 'B',
  'activity': 'preparing breakfast',
  'description': 'B continues to get water into the sauce pan.'},
 {'time': '07:24:09',
  'sensor': 'kitchen counter mov',
  'sensor_status': 'turned OFF',
  'subject': 'B',
  'activity': 'preparing breakfast',
  'description': 'nan'},
 {'time': '07:24:14',
  'sensor': 'kitchen sink mov',
  'sensor_status': 'turned OFF',
  'subject': 'B',
  'activity': 'preparing breakfast',
  'description': 'B continues to get water into the sauce pan.'},
 {'time': '07:24:17',
  'sensor': 'kitchen coffee machine wattmeter',
  'sensor_status': 'turned ON',
  'subject': 'A',
  'activity': 'preparing drinks',
  'description': 'After taking the cup, A starts using the coffee machine to brew coffee.'},
 {'time': '07:24:23',
  'sensor': 'kitchen induction stove wattmeter',
  'sensor_status': 'turned ON',
  'subject': 'B',
  'activity': 'preparing breakfast',
  'description': 'B uses the electric stove to heat water in the kettle.'},
 {'time': '07:24:29',
  'sensor': 'kitchen cabinet door',
  'sensor_status': 'OPENED',
  'subject': 'A',
  'activity': 'preparing drinks',
  'description': 'While waiting for the coffee machine to brew coffee, A opens the kitchen cabinet door.'},
 {'time': '07:24:30',
  'sensor': 'kitchen cabinet door',
  'sensor_status': 'CLOSED',
  'subject': 'A',
  'activity': 'preparing drinks',
  'description': 'A takes out dishes from the kitchen cabinet, moves them to the dining room, and places the dishes on the table.'},
 {'time': '07:24:39',
  'sensor': 'nan',
  'sensor_status': 'nan',
  'subject': 'B',
  'activity': 'preparing breakfast',
  'description': 'B takes a knife and fork from the dish drying rack on the kitchen counter.'},
 {'time': '07:24:43',
  'sensor': 'nan',
  'sensor_status': 'nan',
  'subject': 'B',
  'activity': 'preparing breakfast',
  'description': 'B walks into the kitchen dining room, carrying the knife and fork next to the dishes.'},
 {'time': '07:24:54',
  'sensor': 'nan',
  'sensor_status': 'nan',
  'subject': 'A',
  'activity': 'preparing drinks',
  'description': 'A returns to the coffee machine, taking away the brewed coffee.'},
 {'time': '07:24:55',
  'sensor': 'kitchen fridge door',
  'sensor_status': 'OPENED',
  'subject': 'B',
  'activity': 'preparing breakfast',
  'description': 'B returns to the kitchen and opens the fridge.'},
 {'time': '07:25:00',
  'sensor': 'kitchen sink mov',
  'sensor_status': 'turned ON',
  'subject': 'B',
  'activity': 'preparing breakfast',
  'description': 'B is currently checking the food in the fridge, taking out a carton of eggs.'},
 {'time': '07:25:11',
  'sensor': 'kitchen fridge door',
  'sensor_status': 'CLOSED',
  'subject': 'B',
  'activity': 'preparing breakfast',
  'description': 'B closes the fridge door.'},
 {'time': '07:25:15',
  'sensor': 'kitchen sink mov',
  'sensor_status': 'turned OFF',
  'subject': 'B',
  'activity': 'preparing breakfast',
  'description': 'B opens the fridge and takes out a few eggs into the sauce pan.'},
 {'time': '07:25:16',
  'sensor': 'kitchen fridge door',
  'sensor_status': 'OPENED',
  'subject': 'B',
  'activity': 'preparing breakfast',
  'description': 'B reopens the fridge and puts the remaining eggs back.'},
 {'time': '07:25:17',
  'sensor': 'nan',
  'sensor_status': 'nan',
  'subject': 'A',
  'activity': 'preparing drinks',
  'description': 'A places well-prepared coffee on the dining table.'},
 {'time': '07:25:19',
  'sensor': 'kitchen fridge door',
  'sensor_status': 'CLOSED',
  'subject': 'B',
  'activity': 'preparing breakfast',
  'description': 'B closes the fridge door and then returns to the stove side, stirs the saucepan.'},
 {'time': '07:25:23',
  'sensor': 'bedroom_2 door',
  'sensor_status': 'OPENED',
  'subject': 'C',
  'activity': 'bedroom personal activity',
  'description': 'C gets out of bed after opening the door to bedroom_2.'},
 {'time': '07:25:28',
  'sensor': 'bedroom_2 door',
  'sensor_status': 'CLOSED',
  'subject': 'C',
  'activity': 'bedroom personal activity',
  'description': 'C leaves bedroom_2 and closes the room door.'},
 {'time': '07:25:29',
  'sensor': 'nan',
  'sensor_status': 'nan',
  'subject': 'A',
  'activity': 'others',
  'description': 'A walks from the dining table to the kitchen.'},
 {'time': '07:25:33',
  'sensor': 'bathroom global mov',
  'sensor_status': 'turned ON',
  'subject': 'C',
  'activity': 'personal washing',
  'description': 'After leaving bedroom_2, C walks into the bathroom.'},
 {'time': '07:25:38',
  'sensor': 'bathroom sink mov',
  'sensor_status': 'turned ON',
  'subject': 'C',
  'activity': 'personal washing',
  'description': 'C begins their morning routine at the bathroom sink.'},
 {'time': '07:25:44',
  'sensor': 'bathroom sink mov',
  'sensor_status': 'turned OFF',
  'subject': 'C',
  'activity': 'personal washing',
  'description': 'nan'},
 {'time': '07:25:47',
  'sensor': 'bathroom sink mov',
  'sensor_status': 'turned ON',
  'subject': 'C',
  'activity': 'personal washing',
  'description': 'nan'},
 {'time': '07:25:53',
  'sensor': 'dining room chair_3 contact',
  'sensor_status': 'OPENED',
  'subject': 'A',
  'activity': 'others',
  'description': 'A walks to the dining table and sits down on chair_3.'},
 {'time': '07:25:58',
  'sensor': 'dining room chair_3 contact',
  'sensor_status': 'CLOSED',
  'subject': 'A',
  'activity': 'grabing food or drinks',
  'description': "A remembers that there is still bread that hasn't been taken out, so they stand up from chair_3."},
 {'time': '07:25:59',
  'sensor': 'bathroom sink mov',
  'sensor_status': 'turned OFF',
  'subject': 'C',
  'activity': 'personal washing',
  'description': 'C finishes their morning routine.'},
 {'time': '07:26:02',
  'sensor': 'dining room food cabinet door',
  'sensor_status': 'OPENED',
  'subject': 'A',
  'activity': 'grabing food or drinks',
  'description': 'A walks to the food cabinet and opens the cabinet door.'},
 {'time': '07:26:20',
  'sensor': 'dining room food cabinet door',
  'sensor_status': 'CLOSED',
  'subject': 'A',
  'activity': 'grabing food or drinks',
  'description': 'A takes out bread from the food cabinet.'},
 {'time': '07:26:21',
  'sensor': 'bathroom toilet contact',
  'sensor_status': 'CLOSED',
  'subject': 'C',
  'activity': 'using toilet',
  'description': 'C begins to use the bathroom toilet.'},
 {'time': '07:26:21',
  'sensor': 'kitchen range hood wattmeter',
  'sensor_status': 'turned ON',
  'subject': 'B',
  'activity': 'preparing breakfast',
  'description': 'B opens the range hood to extract oil fumes while cooking.'},
 {'time': '07:26:37',
  'sensor': 'bedroom_1 door',
  'sensor_status': 'OPENED',
  'subject': 'A',
  'activity': 'bedroom personal activity',
  'description': 'A walks to the bedroom_1 door and opens the bedroom_1 room door.'},
 {'time': '07:26:38',
  'sensor': 'bathroom toilet contact',
  'sensor_status': 'OPENED',
  'subject': 'C',
  'activity': 'using toilet',
  'description': 'C finishes using the toilet.'},
 {'time': '07:26:41',
  'sensor': 'bedroom_1 door',
  'sensor_status': 'CLOSED',
  'subject': 'A',
  'activity': 'bedroom personal activity',
  'description': 'A enters bedroom_1, closes the room door, and starts to take the bedspread from the room.'},
 {'time': '07:26:47',
  'sensor': 'bathroom sink mov',
  'sensor_status': 'turned ON',
  'subject': 'C',
  'activity': 'using toilet',
  'description': 'C washes their hands clean after using the toilet.'},
 {'time': '07:26:49',
  'sensor': 'bathroom sink mov',
  'sensor_status': 'turned OFF',
  'subject': 'C',
  'activity': 'using toilet',
  'description': 'C finishes washing their hands.'},
 {'time': '07:27:04',
  'sensor': 'bedroom_1 door',
  'sensor_status': 'OPENED',
  'subject': 'A',
  'activity': 'bedroom personal activity',
  'description': 'A opens the room door after taking the bedspread.'},
 {'time': '07:27:05',
  'sensor': 'bathroom global mov',
  'sensor_status': 'turned OFF',
  'subject': 'C',
  'activity': 'using toilet',
  'description': 'C has left the bathroom.'},
 {'time': '07:27:07',
  'sensor': 'living room couch mov',
  'sensor_status': 'turned ON',
  'subject': 'C',
  'activity': 'resting on the couch or the chairs',
  'description': 'C sits down on the living room couch.'},
 {'time': '07:27:10',
  'sensor': 'bedroom_1 door',
  'sensor_status': 'CLOSED',
  'subject': 'A',
  'activity': 'bedroom personal activity',
  'description': 'A walks past bedroom_1, then closes the room door behind them.'},
 {'time': '07:27:16',
  'sensor': 'nan',
  'sensor_status': 'nan',
  'subject': 'A',
  'activity': 'others',
  'description': 'A walks from bedroom_1 towards the kitchen.'},
 {'time': '07:27:17',
  'sensor': 'bathroom global mov',
  'sensor_status': 'turned ON',
  'subject': 'B',
  'activity': 'using toilet',
  'description': 'B waits for the food to cook, leaving the kitchen stove and entering the bathroom.'},
 {'time': '07:27:21',
  'sensor': 'nan',
  'sensor_status': 'nan',
  'subject': 'A',
  'activity': 'preparing breakfast',
  'description': 'A arrives at the kitchen stove and begins to assist B with the work, taking off the food that is currently cooking.'},
 {'time': '07:27:29',
  'sensor': 'bathroom toilet contact',
  'sensor_status': 'CLOSED',
  'subject': 'B',
  'activity': 'using toilet',
  'description': 'B starts to use the toilet.'},
 {'time': '07:27:35',
  'sensor': 'living room couch mov',
  'sensor_status': 'turned OFF',
  'subject': 'C',
  'activity': 'resting on the couch or the chairs',
  'description': 'C is still on the couch, currently checking their phone'},
 {'time': '07:27:40',
  'sensor': 'kitchen counter mov',
  'sensor_status': 'turned ON',
  'subject': 'A',
  'activity': 'preparing breakfast',
  'description': 'A is also organizing the kitchen counter while preparing the utensils.'},
 {'time': '07:27:42',
  'sensor': 'kitchen counter mov',
  'sensor_status': 'turned OFF',
  'subject': 'A',
  'activity': 'preparing breakfast',
  'description': 'nan'},
 {'time': '07:27:48',
  'sensor': 'bathroom toilet contact',
  'sensor_status': 'OPENED',
  'subject': 'B',
  'activity': 'using toilet',
  'description': 'B finishes using the toilet'},
 {'time': '07:27:53',
  'sensor': 'bathroom sink mov',
  'sensor_status': 'turned ON',
  'subject': 'B',
  'activity': 'using toilet',
  'description': 'After B uses the toilet, they wash their hands in the sink and proceed to rinse off in the morning activity'},
 {'time': '07:27:56',
  'sensor': 'living room couch mov',
  'sensor_status': 'turned ON',
  'subject': 'C',
  'activity': 'resting on the couch or the chairs',
  'description': 'C stands up from the couch'},
 {'time': '07:28:01',
  'sensor': 'bedroom_2 door',
  'sensor_status': 'OPENED',
  'subject': 'C',
  'activity': 'bedroom personal activity',
  'description': 'C arrives at bedroom_2 door and opens the room door'},
 {'time': '07:28:01',
  'sensor': 'living room couch mov',
  'sensor_status': 'turned OFF',
  'subject': 'C',
  'activity': 'bedroom personal activity',
  'description': 'C leaves the living room'},
 {'time': '07:28:06',
  'sensor': 'bedroom_2 door',
  'sensor_status': 'CLOSED',
  'subject': 'C',
  'activity': 'bedroom personal activity',
  'description': 'C enters the room and closes the room door'},
 {'time': '07:28:07',
  'sensor': 'kitchen fridge door',
  'sensor_status': 'OPENED',
  'subject': 'A',
  'activity': 'preparing breakfast',
  'description': 'A opens the fridge door'},
 {'time': '07:28:11',
  'sensor': 'bathroom sink mov',
  'sensor_status': 'turned OFF',
  'subject': 'B',
  'activity': 'using toilet',
  'description': 'B finishes the morning activity done at the bathroom sink'},
 {'time': '07:28:20',
  'sensor': 'kitchen fridge door',
  'sensor_status': 'CLOSED',
  'subject': 'A',
  'activity': 'preparing breakfast',
  'description': 'After placing the food from the kitchen counter into the fridge, A closes the fridge door'},
 {'time': '07:28:25',
  'sensor': 'bathroom global mov',
  'sensor_status': 'turned OFF',
  'subject': 'B',
  'activity': 'using toilet',
  'description': 'B walks out of the bathroom'},
 {'time': '07:28:33',
  'sensor': 'nan',
  'sensor_status': 'nan',
  'subject': 'B',
  'activity': 'preparing breakfast',
  'description': 'B arrives at the kitchen to check that A is preparing breakfast'},
 {'time': '07:28:38',
  'sensor': 'nan',
  'sensor_status': 'nan',
  'subject': 'B',
  'activity': 'preparing breakfast',
  'description': "B turns off the range hood's exhaust function"},
 {'time': '07:28:41',
  'sensor': 'kitchen induction stove wattmeter',
  'sensor_status': 'turned OFF',
  'subject': 'A, B',
  'activity': 'preparing breakfast',
  'description': "A and B together turn off the induction stove, but due to the stove's residual heat, it remains hot; the efficiency has not yet dropped to zero"},
 {'time': '07:29:09',
  'sensor': 'kitchen range hood wattmeter',
  'sensor_status': 'turned OFF',
  'subject': 'A',
  'activity': 'preparing breakfast',
  'description': "A turns off the range hood's indicator light"},
 {'time': '07:29:18',
  'sensor': 'dining room chair_1 contact',
  'sensor_status': 'OPENED',
  'subject': 'B',
  'activity': 'having breakfast',
  'description': 'B walks to the dining table and sits down on chair_1'},
 {'time': '07:29:18',
  'sensor': 'dining room chair_3 contact',
  'sensor_status': 'OPENED',
  'subject': 'A',
  'activity': 'having breakfast',
  'description': 'A walks to the dining table and sits down on chair_3 to start eating breakfast'},
 {'time': '07:29:19',
  'sensor': 'dining room chair_1 contact',
  'sensor_status': 'CLOSED',
  'subject': 'B',
  'activity': 'having breakfast',
  'description': 'B stands up from chair_1'},
 {'time': '07:29:26',
  'sensor': 'bedroom_2 door',
  'sensor_status': 'OPENED',
  'subject': 'B',
  'activity': 'others',
  'description': 'B closes the bedroom_2 door, then opens the door and calls C to come out for breakfast'},
 {'time': '07:29:37',
  'sensor': 'bedroom_2 door',
  'sensor_status': 'CLOSED',
  'subject': 'B, C',
  'activity': 'others',
  'description': 'C walks out of bedroom_2 with a backpack and closes the bedroom_2 door together with B.'},
 {'time': '07:29:41',
  'sensor': 'nan',
  'sensor_status': 'nan',
  'subject': 'C',
  'activity': 'others',
  'description': 'C places the backpack on the living room couch'},
 {'time': '07:29:43',
  'sensor': 'dining room chair_1 contact',
  'sensor_status': 'OPENED',
  'subject': 'B',
  'activity': 'having breakfast',
  'description': 'B arrives at the dining table and sits down on chair_1 to start eating breakfast'},
 {'time': '07:29:45',
  'sensor': 'dining room chair_2 contact',
  'sensor_status': 'OPENED',
  'subject': 'C',
  'activity': 'having breakfast',
  'description': 'C arrives at the dining table and sits down on chair_2 to start eating breakfast'},
 {'time': '07:30:46',
  'sensor': 'dining room chair_3 contact',
  'sensor_status': 'CLOSED',
  'subject': 'A',
  'activity': 'having breakfast',
  'description': 'A stands up from chair_3'},
 {'time': '07:30:50',
  'sensor': 'kitchen fridge door',
  'sensor_status': 'OPENED',
  'subject': 'A',
  'activity': 'preparing drinks',
  'description': 'A walks towards the kitchen and opens the fridge'},
 {'time': '07:30:51',
  'sensor': 'kitchen fridge door',
  'sensor_status': 'CLOSED',
  'subject': 'A',
  'activity': 'preparing drinks',
  'description': 'A takes the juice out from the fridge, then closes the fridge door'},
 {'time': '07:30:52',
  'sensor': 'kitchen sink mov',
  'sensor_status': 'turned ON',
  'subject': 'A',
  'activity': 'preparing drinks',
  'description': 'A stands up in front of the fridge'},
 {'time': '07:30:53',
  'sensor': 'kitchen counter mov',

In [47]:
har_df = pd.DataFrame(har_data)
har_df.head()

,time,sensor,sensor_status,subject,activity,description
0,07:22:45,bedroom_1 door,OPENED,A,bedroom personal activity,"After getting up in the morning, A opens the d..."
1,07:22:49,bedroom_1 door,CLOSED,A,bedroom personal activity,A walks out of bedroom_1 and then closes the d...
2,07:22:55,bathroom global mov,turned ON,A,using toilet,"After leaving bedroom_1, A walks into the bath..."
3,07:23:04,bathroom toilet contact,CLOSED,A,using toilet,A starts using the toilet in the bathroom.
4,07:23:16,bedroom_1 door,OPENED,B,bedroom personal activity,"After getting up in the morning, B opens the d..."

In [ ]:
def add_cyclical_time_features(df: pd.DataFrame, timestamp_col: str) -> pd.DataFrame:

    ts = pd.to_datetime(df[timestamp_col])

    fractional_hour = ts.dt.hour + (ts.dt.minute / 60.0) + (ts.dt.second / 3600.0)
    radians_24h = 2 * np.pi * (fractional_hour / 24.0)

    df["Hour_X"] = np.cos(radians_24h)
    df["Hour_Y"] = np.sin(radians_24h)

    return df

In [49]:
har_df_2 = add_cyclical_time_features(df=har_df, timestamp_col="time")
har_df_2.head(20)

/var/folders/7j/72bggrrd5q119jndsw6y6dcw0000gn/T/ipykernel_97784/527309033.py:5: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  ts = pd.to_datetime(df[timestamp_col])

,time,sensor,sensor_status,subject,activity,description,Hour_X,Hour_Y
0,07:22:45,bedroom_1 door,OPENED,A,bedroom personal activity,"After getting up in the morning, A opens the d...",-0.353271,0.935521
1,07:22:49,bedroom_1 door,CLOSED,A,bedroom personal activity,A walks out of bedroom_1 and then closes the d...,-0.353543,0.935418
2,07:22:55,bathroom global mov,turned ON,A,using toilet,"After leaving bedroom_1, A walks into the bath...",-0.353951,0.935264
3,07:23:04,bathroom toilet contact,CLOSED,A,using toilet,A starts using the toilet in the bathroom.,-0.354563,0.935032
4,07:23:16,bedroom_1 door,OPENED,B,bedroom personal activity,"After getting up in the morning, B opens the d...",-0.355379,0.934722
5,07:23:19,bathroom toilet contact,OPENED,A,using toilet,A finishes using the toilet in the bathroom.,-0.355583,0.934645
6,07:23:20,bedroom_1 door,CLOSED,B,bedroom personal activity,B walks out of bedroom_1 and then closes the d...,-0.355651,0.934619
7,07:23:25,bedroom_2 door,OPENED,B,bedroom personal activity,"B arrives at the doorway of bedroom_2, then af...",-0.355991,0.934490
8,07:23:25,bathroom sink mov,turned ON,A,using toilet,"After using the toilet, A washes hands in the ...",-0.355991,0.934490
9,07:23:32,bedroom_2 door,CLOSED,B,bedroom personal activity,"After getting up in bedroom_2, B closes the do...",-0.356466,0.934308
10,07:23:38,bathroom sink mov,turned OFF,A,using toilet,A finishes washing hands in the bathroom sink.,-0.356874,0.934153
11,07:23:38,kitchen sink mov,turned ON,B,preparing breakfast,B arrives at the kitchen sink and starts washi...,-0.356874,0.934153
12,07:23:54,kitchen sink mov,turned OFF,B,preparing breakfast,B finishes washing hands.,-0.357961,0.933737
13,07:23:54,bathroom global mov,turned OFF,A,using toilet,A leaves the bathroom and moves to the kitchen.,-0.357961,0.933737
14,07:24:00,kitchen cabinet door,OPENED,B,preparing breakfast,B crouches down and opens the kitchen cabinet ...,-0.358368,0.933580
15,07:24:01,kitchen cabinet door,CLOSED,B,preparing breakfast,"After taking out a sauce pan, B closes the kit...",-0.358436,0.933554
16,07:24:02,kitchen counter mov,turned ON,A,preparing drinks,A takes a dish from the dish drying rack on th...,-0.358504,0.933528
17,07:24:04,kitchen sink mov,turned ON,B,preparing breakfast,B uses the freshly taken sauce pan in the kitc...,-0.358640,0.933476
18,07:24:06,kitchen sink mov,turned OFF,B,preparing breakfast,B uses the freshly taken sauce pan in the kitc...,-0.358775,0.933424
19,07:24:07,kitchen sink mov,turned ON,B,preparing breakfast,B continues to get water into the sauce pan.,-0.358843,0.933398

In [ ]:
SENSOR_RENAME_MAP = {
    "kitchen range hood wattmeter": "hood",
    "kitchen induction stove wattmeter": "stove",
    "kitchen coffee machine wattmeter": "coffee_machine",
    "kitchen microwave wattmeter": "microwave",
    "kitchen kettle wattmeter": "kettle",
    "kitchen counter mov": "kitchen",
    "kitchen cabinet door": "kitchen",
    "kitchen fridge door": "fridge_door",
    "kitchen sink mov": "kitchen",
    "main door": "main door",
    "dining room chair_1 contact": "dining_room",
    "dining room chair_2 contact": "dining_room",
    "dining room chair_3 contact": "dining_room",
    "dining room food cabinet door": "dining_room",
    "living room bookshelf mov": "living_room",
    "living room TV wattmeter": "TV",
    "living room game console wattmeter": "game_console",
    "living room couch mov": "dining_room",
    "bathroom toilet contact": "bathroom",
    "bathroom global mov": "bathroom",
    "bathroom sink mov": "bathroom",
    "bedroom_1 door": "bedroom_1_door",
    "bedroom_2 door sensor": "bedroom_2_door",
    "nan" : "unknown"
}

APPLIANCES = {
    "hood",
    "stove",
    "coffee_machine",
    "microwave",
    "kettle",
    "TV",
    "game_console",
    "unknown"
}

ROOMS = {"kitchen", "dining_room", "living_room", "bathroom"}

DOOR_SENSORS = {"fridge_door", "main door", "bedroom_1_door", "bedroom_2_door"}

def rename_sensor_column(
    df: pd.DataFrame, sensor_col: str = "sensor"
) -> pd.DataFrame:
    """Remaps values in the sensor column using SENSOR_RENAME_MAP.
    """
    cleaned_sensors = df[sensor_col].astype(str).str.strip()
    df[sensor_col] = cleaned_sensors.replace(SENSOR_RENAME_MAP)
    return df

In [52]:
har_df_3 = rename_sensor_column(har_df_2, sensor_col="sensor")
har_df_3.head()

,time,sensor,sensor_status,subject,activity,description,Hour_X,Hour_Y
0,07:22:45,bedroom_1_door,OPENED,A,bedroom personal activity,"After getting up in the morning, A opens the d...",-0.353271,0.935521
1,07:22:49,bedroom_1_door,CLOSED,A,bedroom personal activity,A walks out of bedroom_1 and then closes the d...,-0.353543,0.935418
2,07:22:55,bathroom,turned ON,A,using toilet,"After leaving bedroom_1, A walks into the bath...",-0.353951,0.935264
3,07:23:04,bathroom,CLOSED,A,using toilet,A starts using the toilet in the bathroom.,-0.354563,0.935032
4,07:23:16,bedroom_1_door,OPENED,B,bedroom personal activity,"After getting up in the morning, B opens the d...",-0.355379,0.934722

In [ ]:
def split_sensor_into_three_columns(
    df: pd.DataFrame, sensor_col: str = "sensor"
) -> pd.DataFrame:
    """Splits the sensor column into:
    - 'appliance'
    - 'location'
    - 'door_sensor'
    """
    s = df[sensor_col].astype(str).str.strip()
    df["appliance"] = s.apply(lambda x: x if x in APPLIANCES else "unknown")
    df["location"] = s.apply(lambda x: x if x in ROOMS else "unknown")
    df["door_sensor"] = s.apply(lambda x: x if x in DOOR_SENSORS else "unknown")
    df = df.drop(columns=[sensor_col])
    return df

In [54]:
df_result = split_sensor_into_three_columns(har_df_3, sensor_col="sensor")
df_result.head()

,time,sensor_status,subject,activity,description,Hour_X,Hour_Y,appliance,location,door_sensor
0,07:22:45,OPENED,A,bedroom personal activity,"After getting up in the morning, A opens the d...",-0.353271,0.935521,unknown,unknown,bedroom_1_door
1,07:22:49,CLOSED,A,bedroom personal activity,A walks out of bedroom_1 and then closes the d...,-0.353543,0.935418,unknown,unknown,bedroom_1_door
2,07:22:55,turned ON,A,using toilet,"After leaving bedroom_1, A walks into the bath...",-0.353951,0.935264,unknown,bathroom,unknown
3,07:23:04,CLOSED,A,using toilet,A starts using the toilet in the bathroom.,-0.354563,0.935032,unknown,bathroom,unknown
4,07:23:16,OPENED,B,bedroom personal activity,"After getting up in the morning, B opens the d...",-0.355379,0.934722,unknown,unknown,bedroom_1_door

In [56]:
df_result.drop(columns=["subject", "description", "time"], inplace=True)
df_result.head()

,sensor_status,activity,Hour_X,Hour_Y,appliance,location,door_sensor
0,OPENED,bedroom personal activity,-0.353271,0.935521,unknown,unknown,bedroom_1_door
1,CLOSED,bedroom personal activity,-0.353543,0.935418,unknown,unknown,bedroom_1_door
2,turned ON,using toilet,-0.353951,0.935264,unknown,bathroom,unknown
3,CLOSED,using toilet,-0.354563,0.935032,unknown,bathroom,unknown
4,OPENED,bedroom personal activity,-0.355379,0.934722,unknown,unknown,bedroom_1_door

In [57]:
df_result["sensor_status"].unique()

<StringArray>
['OPENED', 'CLOSED', 'turned ON', 'turned OFF', 'nan']
Length: 5, dtype: str

In [59]:
sensor_status = ['OPENED', 'CLOSED', 'turned ON', 'turned OFF']
df_result["sensor_status"] = df_result["sensor_status"].apply(lambda x: x if x in sensor_status else "unknown")

In [60]:
df_result[df_result['sensor_status']=='nan']

Empty DataFrame
Columns: [sensor_status, activity, Hour_X, Hour_Y, appliance, location, door_sensor]
Index: []

In [62]:
df_result["activity"].unique()

<StringArray>
[         'bedroom personal activity',                       'using toilet',
                'preparing breakfast',                   'preparing drinks',
                             'others',                   'personal washing',
             'grabing food or drinks', 'resting on the couch or the chairs',
                   'having breakfast',                  'grabing tableware',
                     'clearing table',                     'washing dishes',
                        'watching TV',                      'reading books',
   'drinking water, coffee or drinks',                'cleaning appartment',
                      'taking shower',                'playing video games',
       'getting out of the apartment',          'coming into the apartment',
                           'chatting',                    'treating fruits',
            'having fruits or snacks',                           'using pc',
                   'preparing dinner',                      'having dinner',
                'playing board games']
Length: 27, dtype: str

In [63]:
df_result[df_result['activity']=='chatting']

,sensor_status,activity,Hour_X,Hour_Y,appliance,location,door_sensor
1357,OPENED,chatting,-0.892028,0.451981,unknown,dining_room,unknown
1434,CLOSED,chatting,-0.917118,0.398616,unknown,dining_room,unknown
1449,CLOSED,chatting,-0.918906,0.394477,unknown,dining_room,unknown
1460,OPENED,chatting,-0.920902,0.389794,unknown,dining_room,unknown
1463,OPENED,chatting,-0.921299,0.388856,unknown,dining_room,unknown
...,...,...,...,...,...,...,...
8198,turned ON,chatting,0.893175,-0.449709,unknown,dining_room,unknown
8199,turned OFF,chatting,0.893567,-0.448929,unknown,dining_room,unknown
8200,turned ON,chatting,0.893665,-0.448734,unknown,dining_room,unknown
8201,turned OFF,chatting,0.893731,-0.448604,unknown,dining_room,unknown
8202,turned ON,chatting,0.893828,-0.448409,unknown,dining_room,unknown

In [ ]:
ACTIVITY_RENAME_MAP = {
    "using toilet": "using bathroom",
    "personal washing": "using bathroom",
    "preparing drinks": "grabing food or drinks",
    "grabing tableware": "grabing food or drinks",
    "clearing table": "grabing food or drinks",
    "treating fruits": "grabing food or drinks",
    "chatting": "chatting/using the cell-phone",
    "playing board games": "playing board games or puzzles",
}


def remap_activities(
    df: pd.DataFrame, activity_col: str = "activity"
) -> pd.DataFrame:
    """Remaps specific activity names.
    """
    df[activity_col] = (
        df[activity_col].astype(str).str.strip().replace(ACTIVITY_RENAME_MAP)
    )
    return df

In [66]:

df_result_2 = remap_activities(df_result, activity_col="activity")
df_result_2.head()

,sensor_status,activity,Hour_X,Hour_Y,appliance,location,door_sensor
0,OPENED,bedroom personal activity,-0.353271,0.935521,unknown,unknown,bedroom_1_door
1,CLOSED,bedroom personal activity,-0.353543,0.935418,unknown,unknown,bedroom_1_door
2,turned ON,using bathroom,-0.353951,0.935264,unknown,bathroom,unknown
3,CLOSED,using bathroom,-0.354563,0.935032,unknown,bathroom,unknown
4,OPENED,bedroom personal activity,-0.355379,0.934722,unknown,unknown,bedroom_1_door

In [68]:
df_result[df_result['activity']=='chatting/using the cell-phone']

,sensor_status,activity,Hour_X,Hour_Y,appliance,location,door_sensor
1357,OPENED,chatting/using the cell-phone,-0.892028,0.451981,unknown,dining_room,unknown
1434,CLOSED,chatting/using the cell-phone,-0.917118,0.398616,unknown,dining_room,unknown
1449,CLOSED,chatting/using the cell-phone,-0.918906,0.394477,unknown,dining_room,unknown
1460,OPENED,chatting/using the cell-phone,-0.920902,0.389794,unknown,dining_room,unknown
1463,OPENED,chatting/using the cell-phone,-0.921299,0.388856,unknown,dining_room,unknown
...,...,...,...,...,...,...,...
8198,turned ON,chatting/using the cell-phone,0.893175,-0.449709,unknown,dining_room,unknown
8199,turned OFF,chatting/using the cell-phone,0.893567,-0.448929,unknown,dining_room,unknown
8200,turned ON,chatting/using the cell-phone,0.893665,-0.448734,unknown,dining_room,unknown
8201,turned OFF,chatting/using the cell-phone,0.893731,-0.448604,unknown,dining_room,unknown
8202,turned ON,chatting/using the cell-phone,0.893828,-0.448409,unknown,dining_room,unknown

In [71]:
len(df_result_2)

8203

In [76]:
Sensor_Status_RENAME_MAP = {
    "OPENED": "ON",
    "CLOSED": "OFF",
    "turned ON": "ON",
    "turned OFF": "OFF",
    "nan": "unknown",
}


def remap_sensor_status(
    df: pd.DataFrame, sensor_status_col: str = "sensor_status"
) -> pd.DataFrame:
    df[sensor_status_col] = (
        df[sensor_status_col].astype(str).str.strip().replace(Sensor_Status_RENAME_MAP)
    )
    return df

In [77]:
df_result["sensor_status"]

0           OPENED
1           CLOSED
2        turned ON
3           CLOSED
4           OPENED
           ...
8198     turned ON
8199    turned OFF
8200     turned ON
8201    turned OFF
8202     turned ON
Name: sensor_status, Length: 8203, dtype: str

In [78]:

df_result = remap_sensor_status(df_result, sensor_status_col="sensor_status")
df_result.head()

,sensor_status,activity,Hour_X,Hour_Y,appliance,location,door_sensor
0,ON,bedroom personal activity,-0.353271,0.935521,unknown,unknown,bedroom_1_door
1,OFF,bedroom personal activity,-0.353543,0.935418,unknown,unknown,bedroom_1_door
2,ON,using bathroom,-0.353951,0.935264,unknown,bathroom,unknown
3,OFF,using bathroom,-0.354563,0.935032,unknown,bathroom,unknown
4,ON,bedroom personal activity,-0.355379,0.934722,unknown,unknown,bedroom_1_door

In [79]:
df_result.to_csv("/Users/simahamedifar/Documents/VSCode/Agentic_AI_HAR_Sima/MuRAL/MuRAL_for_ML_HAR.csv")